# Generated by Django 3.1.3 on 2020-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipRegister', '0002_auto_20201104_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIpMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'person_ip_mac',
                'managed': False,
            },
        ),
    ]
