# Generated by Django 3.1.3 on 2020-12-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipRegister', '0003_personipmac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personipmac',
            options={'managed': True},
        ),
    ]
