# Generated by Django 3.1.3 on 2020-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipRegister', '0004_auto_20201202_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='personipmac',
            name='test',
            field=models.CharField(default='', max_length=255),
        ),
    ]
