# Generated by Django 3.1.3 on 2020-12-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipRegister', '0005_personipmac_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personipmac',
            name='test',
        ),
    ]
