# Generated by Django 3.1.4 on 2020-12-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipRegister', '0006_remove_personipmac_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personipmac',
            options={},
        ),
    ]
