# Generated by Django 3.1.4 on 2020-12-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointedDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=2)),
                ('appointed_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'appointed_duty',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=3)),
                ('department_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='ManageDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=2)),
                ('manage_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'manage_duty',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=2)),
                ('ocu_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'occupation',
            },
        ),
        migrations.CreateModel(
            name='ProDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=2)),
                ('pro_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pro_duty',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=1)),
                ('sex_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sex',
            },
        ),
    ]
