# Generated by Django 3.1.4 on 2020-12-03 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointedduty',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manageduty',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produty',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sex',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('id_num', models.CharField(max_length=20)),
                ('credentials_no', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('pro_no', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('work_time_first', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('appointed_duty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.appointedduty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.department')),
                ('manage_duty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.manageduty')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.occupation')),
                ('pro_duty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.produty')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.sex')),
            ],
            options={
                'db_table': 'stuff',
            },
        ),
    ]
