# Generated by Django 3.1.3 on 2020-11-28 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': '用户名必须唯一'}, max_length=12, unique=True)),
                ('password', models.CharField(max_length=11)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
